/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/trees/{treeId}/waterings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["submitWatering"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trees/{treeId}/maintenance-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["submitMaintenanceRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trees/{treeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTreeDetails"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trees/{treeId}/interactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getInteractions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trees/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["test"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trees/nearby": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getNearbyTrees"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        WateringInput: {
            userId: string;
            /** Format: double */
            liters?: number;
        };
        TreeInteraction: {
            id?: string;
            treeId?: string;
            /** @enum {string} */
            type?: "MAINTENANCE_REQUEST" | "WATERING";
            /** Format: date-time */
            createdAt?: string;
            details?: {
                [key: string]: unknown;
            };
        };
        MaintenanceRequestInput: {
            requestedBy: string;
            issueType: string;
            description: string;
        };
        TreeSummary: {
            treeId?: string;
            commonName?: string;
            latinName?: string;
            /** Format: int32 */
            diameterAtBreastHeightInches?: number;
            health?: string;
            status?: string;
            problems?: string;
            neighborhoodTabulationAreaName?: string;
            borough?: string;
            address?: string;
            zipCode?: string;
            /** Format: double */
            latitude?: number;
            /** Format: double */
            longitude?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    submitWatering: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                treeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WateringInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TreeInteraction"];
                };
            };
        };
    };
    submitMaintenanceRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                treeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MaintenanceRequestInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TreeInteraction"];
                };
            };
        };
    };
    getTreeDetails: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                treeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TreeSummary"];
                };
            };
        };
    };
    getInteractions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                treeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TreeInteraction"][];
                };
            };
        };
    };
    test: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    getNearbyTrees: {
        parameters: {
            query: {
                latitude: number;
                longitude: number;
                radiusMeters?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TreeSummary"][];
                };
            };
        };
    };
}
